<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Abhilash" name="com.eigenRisk.TestSuite.Exposure_Import" tests="5" failures="0" timestamp="16 Jul 2015 08:31:35 GMT" time="456.106" errors="1">
  <testcase name="importExposure_50MB_ValidFile_Excel" time="37.202" classname="com.eigenRisk.TestSuite.Exposure_Import"/>
  <testcase name="importExposure_InvalidFile_Excel" time="174.900" classname="com.eigenRisk.TestSuite.Exposure_Import">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.eigenRisk.TestSuite.Exposure_Import.importExposure_InvalidFile_Excel(Exposure_Import.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- importExposure_InvalidFile_Excel -->
  <testcase name="importExposure_ValidFile_Excel" time="146.388" classname="com.eigenRisk.TestSuite.Exposure_Import"/>
  <testcase name="importExposure_InvalidFile_CSV" time="48.040" classname="com.eigenRisk.TestSuite.Exposure_Import"/>
  <testcase name="importExposure_ValidFile_CSV" time="49.576" classname="com.eigenRisk.TestSuite.Exposure_Import"/>
</testsuite> <!-- com.eigenRisk.TestSuite.Exposure_Import -->
